name: Bug report
description: Report a bug with the library
labels: bug
assignees: DarkoKukovec
body:
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Library version
      description: Version of the `auth-worker` library you're using
  - type: input
    id: providers
    validations:
      required: false
    attributes:
      label: Providers
      description: Which providers are you using (e.g. `google`)
  - type: textarea
    id: tech-stack
    validations:
      required: false
    attributes:
      label: Tech stack
      description: Which tech stack are you using the lib with?
      placeholder: React, Next.js, Angular, ...
  - type: input
    id: issue-envs
    validations:
      required: true
    attributes:
      label: Environments with the issue
      description: Where does the issue happen
      placeholder: iOS Safari 15, Node.js 14
  - type: input
    id: ok-envs
    attributes:
      label: Environments without the issue
      description: Environments that you've checked and work fine
      placeholder: Chrome 99, Firefox 96, Node.js 16
  - type: textarea
    id: current
    attributes:
      label: Current behavior
      description: What is the issue - the behavior that you think doesn't work as expected
    validations:
      required: true
  - type: textarea
    id: ecpected
    attributes:
      label: Expected behavior
      description: What do you expect to happen instead - the correct behavior
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: 'How do you trigger this bug? Please walk us through it step by step.'
      value: |
        1.
        2.
        3.
        ...
      render: bash
