name: Feature request
description: Describe a feature the lib is missing which you think should be added.
labels: enhancement
assignees: DarkoKukovec
body:
  - type: dropdown
    id: breaking
    validations:
      required: true
    attributes:
      label: Breaking change
      description: Would this change cause a breaking change (where some existing feature would break)?
      options:
        - 'Yes'
        - 'No'
        - I'm not sure
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description: Please describe the feature you're suggesting with as many details as possible
