name: Support request
description: Have a question that isn't answered in the docs? Have an issue you're not able to resolve?
labels: support
assignees: DarkoKukovec
body:
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Library version
      description: Version of the `auth-worker` library you're using
  - type: input
    id: providers
    validations:
      required: false
    attributes:
      label: Providers
      description: Which providers are you using (e.g. `google`)
  - type: textarea
    id: tech-stack
    validations:
      required: false
    attributes:
      label: Tech stack
      description: Which tech stack are you using the lib with?
      placeholder: React, Next.js, Angular, ...
  - type: textarea
    id: issue
    attributes:
      label: Issue description
      description: Please describe your issue with as much details (and examples) as possible
    validations:
      required: true
